---
name: Challenge
include:
- path: scripts/xcodegen/settings.yml
  relativePaths: false
- path: scripts/xcodegen/targetTemplates.yml
  relativePaths: false
- path: libraries/core/DependencyInjector/project.yml
  relativePaths: false
- path: libraries/core/NetworkClient/project.yml
  relativePaths: false
